"""Initial migration

Revision ID: 32ae39a96aca
Revises: 
Create Date: 2024-08-15 17:27:03.651592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ae39a96aca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('highest_streak', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_player_id'), 'player', ['id'], unique=False)
    op.create_table('sudoku',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('puzzle', sa.String(length=255), nullable=False),
    sa.Column('solution', sa.String(length=255), nullable=False),
    sa.Column('best_time', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=255), nullable=True),
    sa.Column('best_player', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['best_player'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sudoku_id'), 'sudoku', ['id'], unique=False)
    op.create_table('player_sudoku',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('sudoku_id', sa.Integer(), nullable=False),
    sa.Column('solve_time', sa.Integer(), nullable=True),
    sa.Column('best_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['sudoku_id'], ['sudoku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_sudoku_id'), 'player_sudoku', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_sudoku_id'), table_name='player_sudoku')
    op.drop_table('player_sudoku')
    op.drop_index(op.f('ix_sudoku_id'), table_name='sudoku')
    op.drop_table('sudoku')
    op.drop_index(op.f('ix_player_id'), table_name='player')
    op.drop_table('player')
    # ### end Alembic commands ###
